---
- name: Include vars
  include_vars: main.yml

- import_role:
    name: devsec.hardening.ssh_hardening

- name: Adding ssh legal banner
  copy:
    dest: "/etc/ssh/banner.txt"
    content: |
      {{ ssh_banner_txt }}
