---
- import_role:
    name: devsec.hardening.os_hardening
  when:
    - inventory_hostname != 'localhost'
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
    os_yum_enabled: false
- name: Install the packages
  apt:
    pkg: 
    - unattended-upgrades
    - chkrootkit
    - lynis
- name: Enabling unattended upgrades
  command: dpkg-reconfigure --priority=low unattended-upgrades
- name: Run chkrootkit
  command: chkrootkit
  tags: [ never, routine ]
- name: Remove unused docker containers
  command: docker container prune -f
  tags: [ never, routine ]
