---
version: '3'
services:
  backup:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/application:${PRIMERO_TAG:-latest}'
    volumes:
      - ${HOME}/backups/backup-attachments:/tmp/
      - ${SCRIPT_DIR}/backup_attachment.rb:/srv/primero/application/backup_attachment.rb
      - ${SCRIPT_DIR}/.last_time_attachment_backup_executed.lock:/srv/primero/application/.last_time_attachment_backup_executed.lock
      - ${PRIMERO_STORAGE}:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
      - docker/local.env
    restart: always
